---
- name: Setup raspi, install Docker, docker-compose & build pihole Docker image
  hosts: all
  vars_files:
   - group_vars/secrets.vault.yml
   - group_vars/docker.yml
   - group_vars/raspi.yml
  roles:
    - setup-raspi
    - setup-docker
    - build-pihole